// SPDX-License-Identifier: Apache-2.0
#include "terminal/WindowsProcess.hpp"
#include <windows.h>
#include <fstream>
#include <filesystem>
#include <sstream>
namespace ai_terminal::terminal {namespace {
std::wstring quote(const std::wstring&s){if(s.empty())return L"\"\"";bool q=s.find_first_of(L" \t\"")!=std::wstring::npos;if(!q)return s;std::wstring o=L"\"";size_t bs=0;for(wchar_t c:s){if(c==L'\\')++bs;else if(c==L'"'){o.append(bs*2+1,L'\\');o+=L'"';bs=0;}else{o.append(bs,L'\\');bs=0;o+=c;}}o.append(bs*2,L'\\');o+=L'"';return o;}
std::wstring cmdline(const ProcessOptions&o){std::wstring s=quote(o.executable);for(auto&a:o.arguments){s+=L' ';s+=quote(a);}return s;}
std::string read(const std::filesystem::path&p,size_t max){std::ifstream f(p,std::ios::binary);if(!f)return{};std::string s;f.seekg(0,std::ios::end);auto n=f.tellg();f.seekg(0);if(n>static_cast<std::streamoff>(max))n=static_cast<std::streamoff>(max);s.resize(static_cast<size_t>(n));f.read(s.data(),n);if(static_cast<size_t>(f.gcount())<s.size())s.resize(static_cast<size_t>(f.gcount()));return s;}
}
ProcessResult WindowsProcess::run(const ProcessOptions&o){ProcessResult r;if(o.executable.empty()){r.error="Executable is empty.";return r;}wchar_t tp[MAX_PATH]{},a[MAX_PATH]{},b[MAX_PATH]{};if(!GetTempPathW(MAX_PATH,tp)||!GetTempFileNameW(tp,L"AIO",0,a)||!GetTempFileNameW(tp,L"AIE",0,b)){r.error="Unable to create temporary output files.";if(a[0])DeleteFileW(a);if(b[0])DeleteFileW(b);return r;}std::filesystem::path ap(a),bp(b);HANDLE ho=CreateFileW(ap.c_str(),GENERIC_READ|GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_TEMPORARY,nullptr);HANDLE he=CreateFileW(bp.c_str(),GENERIC_READ|GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_TEMPORARY,nullptr);if(ho==INVALID_HANDLE_VALUE||he==INVALID_HANDLE_VALUE){r.error="Unable to open temporary output files.";if(ho!=INVALID_HANDLE_VALUE)CloseHandle(ho);if(he!=INVALID_HANDLE_VALUE)CloseHandle(he);DeleteFileW(ap.c_str());DeleteFileW(bp.c_str());return r;}SetHandleInformation(ho,HANDLE_FLAG_INHERIT,HANDLE_FLAG_INHERIT);SetHandleInformation(he,HANDLE_FLAG_INHERIT,HANDLE_FLAG_INHERIT);STARTUPINFOW si{};si.cb=sizeof(si);si.dwFlags=STARTF_USESTDHANDLES;si.hStdInput=GetStdHandle(STD_INPUT_HANDLE);si.hStdOutput=ho;si.hStdError=he;PROCESS_INFORMATION pi{};auto line=cmdline(o);DWORD flags=CREATE_NO_WINDOW|CREATE_NEW_PROCESS_GROUP;BOOL ok=CreateProcessW(nullptr,line.data(),nullptr,nullptr,TRUE,flags,nullptr,o.working_directory.empty()?nullptr:o.working_directory.c_str(),&si,&pi);CloseHandle(ho);CloseHandle(he);if(!ok){r.error="CreateProcessW failed: "+std::to_string(GetLastError());DeleteFileW(ap.c_str());DeleteFileW(bp.c_str());return r;}r.started=true;HANDLE job=CreateJobObjectW(nullptr,nullptr);if(job){JOBOBJECT_EXTENDED_LIMIT_INFORMATION info{};info.BasicLimitInformation.LimitFlags=JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE;SetInformationJobObject(job,JobObjectExtendedLimitInformation,&info,sizeof(info));AssignProcessToJobObject(job,pi.hProcess);}
DWORD waited=0;while(waited<o.timeout_ms){if(o.cancelled&&o.cancelled()){r.cancelled=true;TerminateJobObject(job?job:pi.hProcess,130);break;}std::error_code ec1,ec2;auto out_sz=std::filesystem::file_size(ap,ec1);auto err_sz=std::filesystem::file_size(bp,ec2);if((!ec1&&out_sz>o.max_output_bytes)||(!ec2&&err_sz>o.max_output_bytes)){r.error="Process output limit exceeded.";TerminateJobObject(job?job:pi.hProcess,122);WaitForSingleObject(pi.hProcess,5000);break;}auto w=WaitForSingleObject(pi.hProcess,100);if(w==WAIT_OBJECT_0)break;waited+=100;}if(!r.cancelled&&WaitForSingleObject(pi.hProcess,0)==WAIT_TIMEOUT){r.timed_out=true;TerminateJobObject(job?job:pi.hProcess,124);WaitForSingleObject(pi.hProcess,5000);}DWORD code=1;GetExitCodeProcess(pi.hProcess,&code);r.exit_code=static_cast<int>(code);CloseHandle(pi.hThread);CloseHandle(pi.hProcess);if(job)CloseHandle(job);r.stdout_text=read(ap,o.max_output_bytes);r.stderr_text=read(bp,o.max_output_bytes);DeleteFileW(ap.c_str());DeleteFileW(bp.c_str());if(r.timed_out)r.error="Process timed out.";else if(r.cancelled)r.error="Process cancelled.";return r;}
}
