// SPDX-License-Identifier: Apache-2.0
#include "ai/GeminiProvider.hpp"
#include <windows.h>
#include <winhttp.h>
#include <cstdlib>
#include <nlohmann/json.hpp>
namespace ai_terminal::ai {namespace {
std::string env(const char*n){char*v=nullptr;size_t z=0;if(_dupenv_s(&v,&z,n)||!v)return{};std::string s(v,z?z-1:0);free(v);return s;}
std::wstring w(const std::string&s){if(s.empty())return{};int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);if(n<=0)return{};std::wstring o(n,L'\0');MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),o.data(),n);return o;}
AIResponse post(const std::string&body,const std::string&key){AIResponse r;auto h=WinHttpOpen(L"AI-Terminal/1.0.0",WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,nullptr,nullptr,0);if(!h){r.error="WinHttpOpen failed";return r;}auto c=WinHttpConnect(h,L"generativelanguage.googleapis.com",INTERNET_DEFAULT_HTTPS_PORT,0);if(!c){r.error="WinHttpConnect failed";WinHttpCloseHandle(h);return r;}auto q=WinHttpOpenRequest(c,L"POST",L"/v1beta/interactions",nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,WINHTTP_FLAG_SECURE);if(!q){r.error="WinHttpOpenRequest failed";WinHttpCloseHandle(c);WinHttpCloseHandle(h);return r;}auto headers=L"Content-Type: application/json\r\nx-goog-api-key: "+w(key)+L"\r\n";if(!WinHttpSendRequest(q,headers.c_str(),(DWORD)-1L,(void*)body.data(),(DWORD)body.size(),(DWORD)body.size(),0)||!WinHttpReceiveResponse(q,nullptr)){r.error="Gemini HTTP request failed: "+std::to_string(GetLastError());WinHttpCloseHandle(q);WinHttpCloseHandle(c);WinHttpCloseHandle(h);return r;}DWORD status=0,sz=sizeof(status);WinHttpQueryHeaders(q,WINHTTP_QUERY_STATUS_CODE|WINHTTP_QUERY_FLAG_NUMBER,WINHTTP_HEADER_NAME_BY_INDEX,&status,&sz,WINHTTP_NO_HEADER_INDEX);r.http_status=status;std::string raw;for(;;){DWORD a=0;if(!WinHttpQueryDataAvailable(q,&a)||!a)break;std::string b(a,'\0');DWORD got=0;if(!WinHttpReadData(q,b.data(),a,&got))break;raw.append(b,0,got);}WinHttpCloseHandle(q);WinHttpCloseHandle(c);WinHttpCloseHandle(h);try{auto j=nlohmann::json::parse(raw);if(status<200||status>=300){r.error=j.value("error",nlohmann::json::object()).value("message",raw);return r;}r.ok=true;r.interaction_id=j.value("id","");if(j.contains("steps")&&j["steps"].is_array())for(auto&s:j["steps"]){auto t=s.value("type","");if(t=="function_call"){FunctionCall f;f.id=s.value("id","");f.name=s.value("name","");f.arguments=s.value("arguments",nlohmann::json::object());r.function_calls.push_back(std::move(f));}else if(t=="model_output"&&s.contains("content"))for(auto&c2:s["content"])if(c2.value("type","")=="text")r.text+=c2.value("text","");}r.requires_action=!r.function_calls.empty();}catch(const std::exception&e){r.ok=false;r.error=std::string("Invalid Gemini response: ")+e.what();}return r;}
}
GeminiProvider::GeminiProvider(std::string m):model_(std::move(m)){}
AIResponse GeminiProvider::send(const std::vector<ChatMessage>& history,const std::string&sys,const std::vector<nlohmann::json>&tools){auto key=env("GEMINI_API_KEY");if(key.empty())return {false,{},"GEMINI_API_KEY is not set.",0,{},{},false};nlohmann::json input=nlohmann::json::array();for(const auto&m:history)input.push_back({{"type",m.role=="user"?"user_input":"model_output"},{"content",m.text}});nlohmann::json j={{"model",model_},{"input",input},{"store",true},{"tools",tools}};if(!sys.empty())j["system_instruction"]=sys;return post(j.dump(),key);}
AIResponse GeminiProvider::send_function_results(const std::string&id,const std::vector<FunctionResultInput>&rs,const std::vector<nlohmann::json>&tools,const std::string&sys){auto key=env("GEMINI_API_KEY");if(key.empty())return {false,{},"GEMINI_API_KEY is not set.",0,{},{},false};nlohmann::json input=nlohmann::json::array();for(const auto&r:rs)input.push_back({{"type","function_result"},{"name",r.name},{"call_id",r.call_id},{"result",nlohmann::json::array({{{"type","text"},{"text",r.result.dump()}}})}});nlohmann::json j={{"model",model_},{"previous_interaction_id",id},{"input",input},{"tools",tools},{"store",true}};if(!sys.empty())j["system_instruction"]=sys;return post(j.dump(),key);}
}
