// SPDX-License-Identifier: Apache-2.0
#include "tools/GitTools.hpp"
#include <cctype>
namespace ai_terminal::tools {namespace {
bool safe_arg(const std::string&s){if(s.empty())return false;for(char c:s)if(std::string("&|<>^\"'`$(){}!\n\r").find(c)!=std::string::npos)return false;return true;}
class Git final:public Tool{std::string op_;std::filesystem::path root_;std::shared_ptr<terminal::WindowsTerminal>t_;public:Git(std::string o,std::filesystem::path r,std::shared_ptr<terminal::WindowsTerminal>t):op_(std::move(o)),root_(std::move(r)),t_(std::move(t)){}std::string name()const override{return"git_"+op_;}std::string description()const override{return"Git operation: "+op_;}nlohmann::json schema()const override{if(op_=="add")return{{"type","object"},{"properties",{{"path",{{"type","string"}}}}},{"required",{"path"}}};if(op_=="commit")return{{"type","object"},{"properties",{{"message",{{"type","string"}}}}},{"required",{"message"}}};if(op_=="checkout")return{{"type","object"},{"properties",{{"branch",{{"type","string"}}}}},{"required",{"branch"}}};return{{"type","object"},{"properties",nlohmann::json::object()}};}security::RiskLevel risk()const override{if(op_=="status"||op_=="diff"||op_=="log"||op_=="branch")return security::RiskLevel::SAFE;return security::RiskLevel::HIGH;}ToolResult execute(const nlohmann::json&a)override{if(!std::filesystem::exists(root_/".git"))return{false,"This workspace is not a Git repository."};std::string cmd="git "+op_;if(op_=="status")cmd+=" --short";else if(op_=="diff")cmd+=" --no-ext-diff --";else if(op_=="log")cmd+=" --oneline -20";else if(op_=="branch")cmd+=" --list";else if(op_=="add"){auto s=a.at("path").get<std::string>();if(!safe_arg(s)||s.rfind("/",0)==0||s.find("..")!=std::string::npos)return{false,"Unsafe Git path."};cmd+=" -- \""+s+"\"";}else if(op_=="commit"){auto s=a.at("message").get<std::string>();if(!safe_arg(s)||s.size()>1000)return{false,"Unsafe commit message."};cmd+=" -m \""+s+"\"";}else if(op_=="checkout"){auto s=a.at("branch").get<std::string>();if(!safe_arg(s)||s.rfind("-",0)==0)return{false,"Unsafe branch name."};cmd+=" "+s;}else return{false,"Unsupported Git operation."};auto r=t_->execute_command(cmd,300000);return{r.started&&!r.timed_out&&r.exit_code==0,r.stdout_text+(!r.stderr_text.empty()?"\nSTDERR:\n"+r.stderr_text:"")+(!r.error.empty()?"\nERROR: "+r.error:""),r.exit_code};}};
}
std::unique_ptr<Tool> make_git_tool(std::string o,const std::filesystem::path&r,const std::shared_ptr<terminal::WindowsTerminal>&t){return std::make_unique<Git>(std::move(o),r,t);}
}
