// SPDX-License-Identifier: Apache-2.0
#include "tools/ProcessTools.hpp"
#include <windows.h>
#include <tlhelp32.h>
#include <nlohmann/json.hpp>
namespace ai_terminal::tools {namespace {
class List final:public Tool{public:std::string name()const override{return"list_processes";}std::string description()const override{return"List running Windows processes.";}nlohmann::json schema()const override{return{{"type","object"},{"properties",nlohmann::json::object()}};}security::RiskLevel risk()const override{return security::RiskLevel::SAFE;}ToolResult execute(const nlohmann::json&)override{HANDLE h=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);if(h==INVALID_HANDLE_VALUE)return{false,"CreateToolhelp32Snapshot failed."};PROCESSENTRY32W e{};e.dwSize=sizeof(e);nlohmann::json a=nlohmann::json::array();if(Process32FirstW(h,&e))do{char n[512]{};WideCharToMultiByte(CP_UTF8,0,e.szExeFile,-1,n,sizeof(n),nullptr,nullptr);a.push_back({{"pid",e.th32ProcessID},{"parent_pid",e.th32ParentProcessID},{"name",n}});}while(Process32NextW(h,&e));CloseHandle(h);return{true,a.dump(2)};}};
class Info final:public Tool{public:std::string name()const override{return"get_process_info";}std::string description()const override{return"Return basic information for a Windows process ID.";}nlohmann::json schema()const override{return{{"type","object"},{"properties",{{"pid",{{"type","integer"}}}}},{"required",{"pid"}}};}security::RiskLevel risk()const override{return security::RiskLevel::LOW;}ToolResult execute(const nlohmann::json&a)override{DWORD pid=a.at("pid").get<DWORD>();HANDLE h=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid);if(!h)return{false,"Unable to open process; access denied or process exited."};wchar_t path[MAX_PATH*4]{};DWORD n=sizeof(path)/sizeof(wchar_t);QueryFullProcessImageNameW(h,0,path,&n);CloseHandle(h);int z=WideCharToMultiByte(CP_UTF8,0,path,-1,nullptr,0,nullptr,nullptr);std::string p(z?z:0,'\0');if(z) { WideCharToMultiByte(CP_UTF8,0,path,-1,p.data(),z,nullptr,nullptr); if(!p.empty()&&p.back()=='\0')p.pop_back(); }return{true,nlohmann::json({{"pid",pid},{"image_path",p}}).dump(2)};}};
class Term final:public Tool{public:std::string name()const override{return"terminate_process";}std::string description()const override{return"Terminate a Windows process by PID; destructive and permission protected.";}nlohmann::json schema()const override{return{{"type","object"},{"properties",{{"pid",{{"type","integer"}}}}},{"required",{"pid"}}};}security::RiskLevel risk()const override{return security::RiskLevel::HIGH;}ToolResult execute(const nlohmann::json&a)override{DWORD pid=a.at("pid").get<DWORD>();if(pid==GetCurrentProcessId()||pid<4)return{false,"Refusing to terminate the AI Terminal or protected system PID."};HANDLE h=OpenProcess(PROCESS_TERMINATE,FALSE,pid);if(!h)return{false,"Unable to open process for termination."};BOOL ok=TerminateProcess(h,1);CloseHandle(h);if (ok == FALSE) return {false, "TerminateProcess failed."};
return {true, "Process termination requested."};}};}
std::unique_ptr<Tool> make_list_processes_tool(){return std::make_unique<List>();}std::unique_ptr<Tool> make_process_info_tool(){return std::make_unique<Info>();}std::unique_ptr<Tool> make_terminate_process_tool(){return std::make_unique<Term>();}}
