// SPDX-License-Identifier: Apache-2.0
#include "tools/ProjectTools.hpp"
#include <fstream>
#include <sstream>
namespace ai_terminal::tools {namespace {
class Detect final:public Tool{std::filesystem::path r_;public:explicit Detect(std::filesystem::path r):r_(std::move(r)){}std::string name()const override{return"detect_project_type";}std::string description()const override{return"Detect project systems from concrete marker files.";}nlohmann::json schema()const override{return{{"type","object"},{"properties",nlohmann::json::object()}};}security::RiskLevel risk()const override{return security::RiskLevel::SAFE;}ToolResult execute(const nlohmann::json&)override{nlohmann::json j={{"git",std::filesystem::exists(r_/".git")},{"cmake",std::filesystem::exists(r_/"CMakeLists.txt")},{"ninja",std::filesystem::exists(r_/"build.ninja")},{"visual_studio",false},{"python",std::filesystem::exists(r_/"pyproject.toml")||std::filesystem::exists(r_/"requirements.txt")||std::filesystem::exists(r_/"setup.py")},{"node",std::filesystem::exists(r_/"package.json")},{"rust",std::filesystem::exists(r_/"Cargo.toml")}};for(auto&e:std::filesystem::directory_iterator(r_)){auto ext=e.path().extension().string();if(ext==".sln"||ext==".vcxproj")j["visual_studio"]=true;}return{true,j.dump(2)};}};
class Inspect final:public Tool{std::filesystem::path r_;public:explicit Inspect(std::filesystem::path r):r_(std::move(r)){}std::string name()const override{return"inspect_project";}std::string description()const override{return"Summarize project markers, top-level files, and Git presence.";}nlohmann::json schema()const override{return{{"type","object"},{"properties",nlohmann::json::object()}};}security::RiskLevel risk()const override{return security::RiskLevel::SAFE;}ToolResult execute(const nlohmann::json&)override{nlohmann::json j={{"root",r_.string()},{"entries",nlohmann::json::array()}};size_t n=0;for(auto&e:std::filesystem::directory_iterator(r_)){if(n++>=100)break;j["entries"].push_back(e.path().filename().string());}j["entry_count_limited"]=n>=100;return{true,j.dump(2)};}};
class Build final:public Tool{std::filesystem::path r_;std::shared_ptr<terminal::WindowsTerminal> t_;public:Build(std::filesystem::path r,std::shared_ptr<terminal::WindowsTerminal>t):r_(std::move(r)),t_(std::move(t)){}std::string name()const override{return"build_project";}std::string description()const override{return"Configure/build a detected CMake, Ninja, MSBuild or Visual Studio project.";}nlohmann::json schema()const override{return{{"type","object"},{"properties",{{"configuration",{{"type","string"},{"description","Release or Debug; defaults to Release."}}}}}}; }security::RiskLevel risk()const override{return security::RiskLevel::MEDIUM;}ToolResult execute(const nlohmann::json&a)override{auto cfg=a.value("configuration",std::string("Release"));if(cfg!="Release"&&cfg!="Debug")return{false,"configuration must be Release or Debug."};terminal::CommandResult r;if(std::filesystem::exists(r_/"CMakeLists.txt")){r=t_->execute_command("cmake -S . -B build -G \"Visual Studio 17 2022\" -A x64",300000);if(r.exit_code==0)r=t_->execute_command("cmake --build build --config "+cfg+" --parallel",600000);}else if(std::filesystem::exists(r_/"build.ninja")){r=t_->execute_command("ninja -C .",600000);}else{std::filesystem::path sln;for(auto&e:std::filesystem::directory_iterator(r_))if(e.path().extension()==".sln"){sln=e.path();break;}if(!sln.empty())r=t_->execute_command("msbuild \""+sln.filename().string()+"\" /m /p:Configuration="+cfg+"",600000);else return{false,"No supported build system detected."};}nlohmann::json j={{"started",r.started},{"exit_code",r.exit_code},{"timed_out",r.timed_out},{"stdout",r.stdout_text},{"stderr",r.stderr_text}};if(!r.error.empty())j["error"]=r.error;return{r.started&&!r.timed_out&&r.exit_code==0,j.dump(2),r.exit_code};}};
class Test final:public Tool{std::filesystem::path r_;std::shared_ptr<terminal::WindowsTerminal> t_;public:Test(std::filesystem::path r,std::shared_ptr<terminal::WindowsTerminal>t):r_(std::move(r)),t_(std::move(t)){}std::string name()const override{return"test_project";}std::string description()const override{return"Run CTest for a CMake build when available.";}nlohmann::json schema()const override{return{{"type","object"},{"properties",{{"configuration",{{"type","string"}}}}}};}security::RiskLevel risk()const override{return security::RiskLevel::MEDIUM;}ToolResult execute(const nlohmann::json&a)override{auto cfg=a.value("configuration",std::string("Release"));if(!std::filesystem::exists(r_/"build"))return{false,"Build directory does not exist."};auto r=t_->execute_command("ctest --test-dir build -C "+cfg+" --output-on-failure",600000);nlohmann::json j={{"exit_code",r.exit_code},{"stdout",r.stdout_text},{"stderr",r.stderr_text},{"timed_out",r.timed_out}};return{r.started&&!r.timed_out&&r.exit_code==0,j.dump(2),r.exit_code};}};
}
std::unique_ptr<Tool> make_detect_project_type_tool(const std::filesystem::path&r){return std::make_unique<Detect>(r);}std::unique_ptr<Tool> make_inspect_project_tool(const std::filesystem::path&r){return std::make_unique<Inspect>(r);}std::unique_ptr<Tool> make_build_project_tool(const std::filesystem::path&r,const std::shared_ptr<terminal::WindowsTerminal>&t){return std::make_unique<Build>(r,t);}std::unique_ptr<Tool> make_test_project_tool(const std::filesystem::path&r,const std::shared_ptr<terminal::WindowsTerminal>&t){return std::make_unique<Test>(r,t);}
}
